pluginManagement {
    repositories {
        maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url "https://maven.aliyun.com/repository/spring" }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = "shortlink"

include(
    "shortlink-common",
    "shortlink-core",
    "shortlink-cache",
    "shortlink-analytics",
    "shortlink-admin",
    "shortlink-openapi",
    "shortlink-sdk"
)